// Code generated by MockGen. DO NOT EDIT.
// Source: main_test.go
//
// Generated by this command:
//
//	mockgen -source=main_test.go -destination=mocks/main_test_mock.go
//

// Package mock_main_test is a generated GoMock package.
package mock_main_test

import (
	reflect "reflect"

	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	gomock "go.uber.org/mock/gomock"
)

// MockClient_Interface is a mock of Client_Interface interface.
type MockClient_Interface struct {
	ctrl     *gomock.Controller
	recorder *MockClient_InterfaceMockRecorder
}

// MockClient_InterfaceMockRecorder is the mock recorder for MockClient_Interface.
type MockClient_InterfaceMockRecorder struct {
	mock *MockClient_Interface
}

// NewMockClient_Interface creates a new mock instance.
func NewMockClient_Interface(ctrl *gomock.Controller) *MockClient_Interface {
	mock := &MockClient_Interface{ctrl: ctrl}
	mock.recorder = &MockClient_InterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient_Interface) EXPECT() *MockClient_InterfaceMockRecorder {
	return m.recorder
}

// RetrieveSqsMessage mocks base method.
func (m *MockClient_Interface) RetrieveSqsMessage(arg0 *sqs.Client, arg1 string, arg2 bool) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveSqsMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RetrieveSqsMessage indicates an expected call of RetrieveSqsMessage.
func (mr *MockClient_InterfaceMockRecorder) RetrieveSqsMessage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveSqsMessage", reflect.TypeOf((*MockClient_Interface)(nil).RetrieveSqsMessage), arg0, arg1, arg2)
}
